name: manual change, si inferieur a 30 minutes, error

on:
  workflow_dispatch:

jobs:
  manual-change:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Rename file
      run: |
        # date en minute
        date=$(date +"%Y-%m-%d-%H-%M")
        
        # si la minute actuelle est inférieure à 30
        if [ $(date +"%M") -lt 30 ]; then
          # on copie le fichier error.json dans temp.json
          cp public/error.json public/temp.json
        else
          # on copie le fichier success.json dans temp.json
          cp public/success.json public/temp.json
        fi
      

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public

