name: Build2test

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Rename file
      run: |
        cp public/actual2.json public/temp2.json
        cp public/actual1.json public/actual2.json
        cp public/temp2.json public/actual1.json

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public

